# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  flood:

    # Build with github clone
    image: lmilcent/flood:20191219-distroless

    # Container name
    container_name: flood


    # -----------
    # COMPILATION
    # -----------
    build:
        context: ./flood/
        dockerfile: Dockerfile


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false

    # Add a tty
    tty: false

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:dl.lmilcent.com"
      traefik.port: "3000"
      traefik.backend: "rTorrent"
      traefik.docker.network: "proxy"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.protocol: "http"

    # Environment variables
    # For secrets with host environment variables
    #environment: 
    #  TEST_ENV_SECRET: ${ENV_SECRET}
    # Public variables
    env_file: ./flood/default.env
      
    # Volumes
    volumes:
      - rtorrent-flood-db:/app/flood/flood-db:rw
    volumes_from:
      - rtorrent


    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 0.5
    mem_limit: 150m
    memswap_limit: 150m


    # -------
    # NETWORK
    # -------
    
    # Expose port to linked services (internal only)
    #expose:
    
    # Expose port to ALL
    #ports:

    # Network
    networks:
      - proxy
      - rtorrent-backend


    # -----
    # OTHER
    # -----
    
    # Override entrypoints and command
    #entrypoint: /bin/bash
    #command: "printenv | grep TEST"


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL

    cap_add:
      - DAC_OVERRIDE




  # Service name
  rtorrent:

    # Build with github clone
    image: lmilcent/rtorrent:alpine

    # Container name
    container_name: rtorrent


    # -----------
    # COMPILATION
    # -----------
    build:
        context: ./rtorrent/
        dockerfile: Dockerfile


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false

    # Add a tty
    tty: true

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 10s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    #labels:

    # Environment variables
    env_file: ./rtorrent/default.env
      
    # Volumes
    volumes:
      - /data/medias/downloaded:/app/rtorrent/download:rw
      - rtorrent-config:/app/rtorrent/config:rw


    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 2
    mem_limit: 1024m
    memswap_limit: 1024m


    # -------
    # NETWORK
    # -------
    
    # Expose port to linked services (internal only)
    #expose:
    
    # Expose port to ALL
    #ports:

    # Network
    networks:
      - proxy
      - rtorrent-backend


    # -----
    # OTHER
    # -----
    
    # Override entrypoints and command
    #entrypoint: /bin/bash
    #command: "printenv | grep TEST"


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL

    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
      - DAC_OVERRIDE


# ----------------------------
# CREATION: NETWORKS & VOLUMES
# ----------------------------
volumes:
  rtorrent-flood-db:
    name: rtorrent-flood-db
  rtorrent-config:
    name: rtorrent-config

networks:
  # Join an existing network
  proxy:
    name: proxy

  rtorrent-backend:
    name: rtorrent-backend
