# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513
version: '2.4'

services:

  flood:

    image: lmilcent/flood:20201203-alpine
    container_name: flood

    # Compilation
    build:
      context: ./flood/
      dockerfile: Dockerfile

    # Mode interactive
    stdin_open: false
    tty: false

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM

    labels:
      traefik.enable: true
      traefik.http.routers.flood.entrypoints: websecure,web
      traefik.http.routers.flood.rule: Host(`dl.lmilcent.com`) || Host(`dl.milcent.co`)
      # TLS
      traefik.http.routers.flood.tls.certresolver: certMilcent
      # already applied?
      #traefik.http.routers.flood.tls.options: TLSOptions@file
      # Middlewares & Services
      traefik.http.routers.flood.middlewares: flood-compress
      traefik.http.middlewares.flood-compress.compress: true
      # Container communication
      traefik.http.services.flood.loadbalancer.server.port: 3000
      traefik.http.services.flood.loadbalancer.server.scheme: http

    # Public variables
    environment:
      FLOOD_SECRET: ${FLOOD_SECRET}
      
    # Volume
    # SELinux labels: Z = not shared, z = shared)
    volumes:
      - /data/containers-data/flood:/app/flood/flood-db:z
    volumes_from:
      - rtorrent

    # Limit resources
    cpus: 1
    mem_limit: 256m
    memswap_limit: 256m
    pids_limit: 50 # 11 usually

    # Network
    networks:
      - proxy
      - rtorrent-backend
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL

    cap_add:
      - DAC_OVERRIDE
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID



  # Service name
  rtorrent:

    image: lmilcent/rtorrent:20201203-alpine
    container_name: rtorrent

    build:
      context: ./rtorrent/
      dockerfile: Dockerfile

    # Mode interactive
    stdin_open: false
    tty: true

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 10s
    stop_signal: SIGTERM

    # Volumes
    volumes:
      - /data/containers-data/rtorrent/downloaded/incomplete:/incomplete:z
      - /data/containers-data/rtorrent/config:/app/rtorrent/config:z
      - /data/containers-data/jellyfin/tvshows:/tvshows:z
      - /data/containers-data/jellyfin/movies:/movies:z

    # Limit resources
    cpus: 2
    mem_limit: 1024m
    memswap_limit: 1024m
    pids_limit: 50 # 10 usually but 25+ on startup

    # Network
    networks:
      - proxy
      - rtorrent-backend

    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL

    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
      - DAC_OVERRIDE


# Network definitions
networks:
  proxy:
    name: proxy

  rtorrent-backend:
    name: rtorrent-backend
