# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  service:

    # Build image or pull from GitHub
    image: lmilcent/image:tag

    # Container name
    container_name: service


    # -----------
    # COMPILATION
    # -----------
    build:
        context: .
        dockerfile: Dockerfile


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false

    # Add a tty
    tty: false

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:sub.domain.tld"
      traefik.port: "8888"
      traefik.backend: "service"
      traefik.docker.network: "proxy"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.protocol: "http"

    # Environment variables
    # For secrets with host environment variables
    #environment: 
    #  TEST_ENV_SECRET: ${ENV_SECRET}
    # Public variables
    env_file: default.env
      
    # Volumes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- volume-name:/folder

    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 2
    mem_limit: 1024m
    memswap_limit: 1024m


    # -------
    # NETWORK
    # -------
    
    # Expose port to linked services (internal only)
    #expose:
    
    # Expose port to ALL
    #ports:

    # Network
    networks:
      - proxy


    # -----
    # OTHER
    # -----
    
    # Override entrypoints and command
    #entrypoint: /bin/bash
    #command: "printenv | grep TEST"


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    #cap_drop:
    #  - ALL
    #cap_add:
    #  - CAP_CHOWN
    #  - CAP_FOWNER


# ----------------------------
# CREATION: NETWORKS & VOLUMES
# ----------------------------
#volumes:
  # Join an existing volume
  #volume-name:
  #  name: volume-name

  # Create a new volume
  #volume-name

networks:
  # Join an existing network
  proxy:
    name: proxy

# To create a network
#  proxy:
