#!/usr/bin/with-contenv sh

cd /nodebb

# List installed plugins (extracted from nodebb db)
#s6-setuidgid nodebb \
#  node ./nodebb plugins | tail -n +2 | cut -c4- | sed -r 's/( .*$)//g' > /tmp/plugins.txt

i=1
j=1
toInstallTotal=0
toDisableTotal=0

# Get total number of plugin to install and enable
toInstallTotal=$(cat /etc/nodebb/enabled-plugins | wc -l)
# Get total number of plugin to disable
toDisableTotal=$(cat /etc/nodebb/disabled-plugins | wc -l)


# Installing "enabled" plugins
echo && echo "[*] Installing ${toInstallTotal} missing NodeBB plugins"
while read plugin ; do
  # Remove version tag to search folders
  toInstall=$(find node_modules -type d -maxdepth 1 -name "${plugin%@*}" | wc -l)

  # Install only if not already present
  if [ ${toInstall} -eq 0 ] ; then
    echo "  -- ${i} / ${toInstallTotal}: Installing ${plugin}"
    s6-setuidgid nodebb \
      npm install ${plugin} > /dev/null

  # Module already installed
  else
    echo "  -- ${i} / ${toInstallTotal}: Plugin already present (${plugin})"
  fi

  # Increment
  let "i+=1"
done < /etc/nodebb/enabled-plugins


# Disabling "disabled" plugins
echo && echo "[*] Disabling ${toDisableTotal} NodeBB plugins, according to last plugins list export."
while read plugin ; do
  echo && echo "  -- Disabling ${j} / ${toDisableTotal} plugins: ${plugin%@*}"
  s6-setuidgid nodebb node ./nodebb reset -p "${plugin%@*}"

  let "j+=1"
done < /etc/nodebb/disabled-plugins



#
# QUIL COMPOSER PLUGIN
#
# ISSUE: https://github.com/NodeBB/nodebb-plugin-composer-quill/issues/176
# Until NodeBB version < 1.17.x, the module should stay at specific version

# If quill module is present in nodebb plugins
if [ "$(./nodebb plugins | grep quill | wc -l)" -ne 0 ] ; then

  INSTALLED_VERSION=$(cat /nodebb/package.json | grep -m1 version | cut -d '"' -f 4)
  X_X=$(echo "$INSTALLED_VERSION" | cut -d '.' -f 1)
  X_X_X=$(echo "${INSTALLED_VERSION}" | cut -d '.' -f 2)

  # If v1.x
  if [[ ${X_X} -le 1 ]] ; then
    # if v1.16.x
    if [[ ${X_X_X} -le 16 ]] ; then
      echo && echo " [*] WARNING: NodeBB version < 1.17.0, \"nodebb-plugin-composer-quill\" plugin is only compatible in version 1.8.0."
      echo "  -- Deleting the current plugin."
      npm remove nodebb-plugin-composer-quill > /dev/null
      echo "  -- Installing the plugin in correct version."
      npm install nodebb-plugin-composer-quill@1.8.0 > /dev/null
    fi
  fi
fi


# BUILD TO APPLY
echo && echo "[*] Build again NodeBB to apply module changes"
s6-setuidgid nodebb ./nodebb build

exit 0
