#!/usr/bin/with-contenv sh
cd /nodebb
chown -R nodebb:nodebb /etc/nodebb/
if [ ! -e /etc/nodebb/active-plugins ] ; then
  echo "[*] No plugin to install or activate."
  exit
fi

echo "[*] Installing and activating NodeBB plugins"
while read plugin ; do

  echo
  echo "  [*] Installing / upgrading ${plugin}"
  s6-setuidgid nodebb \
    npm install ${plugin}

  echo
  echo "  [*] Activating ${plugin}"
  s6-setuidgid nodebb \
    node ./nodebb activate ${plugin}

done < /etc/nodebb/active-plugins

exit 0
