# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  duplicati:

    # Build Duplicati from last release
    # https://github.com/duplicati/duplicati/releases
    image: lmilcent/duplicati:2.0.5.0-debian

    # Container name
    container_name: duplicati


    # -----------
    # COMPILATION
    # -----------
    build:
        context: .
        dockerfile: Dockerfile


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false

    # Add a tty
    tty: false

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:backup.lmilcent.com"
      traefik.port: "8200"
      traefik.backend: "duplicati"
      traefik.docker.network: "proxy"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.protocol: "http"

    # Environment variables
    # For secrets with host environment variables
    #environment: 
    #  TEST_ENV_SECRET: ${ENV_SECRET}
    # Public variables
    env_file: default.env
      
    # Volumes
    volumes:
      - duplicati-config:/config:rw
      - /etc/localtime:/etc/localtime:ro
      - /home/lmilcent:/backups/lmilcent:rw
      - /home/adeloris:/backups/adeloris:rw
      - /data/duplicati:/restore:rw
      - /docker/volumes:/backups/docker-volumes:rw


    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 2
    mem_limit: 1024m
    memswap_limit: 1024m


    # -------
    # NETWORK
    # -------
    
    # Expose port to linked services (internal only)
    #expose:
    
    # Expose port to ALL
    #ports:

    # Network
    networks:
      - proxy


    # -----
    # OTHER
    # -----
    
    # Override entrypoints and command
    #entrypoint: /bin/bash
    #command: "printenv | grep TEST"


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    #cap_drop:

    #cap_add:
    #  - CAP_CHOWN
    #  - CAP_FOWNER


# ----------------------------
# CREATION: NETWORKS & VOLUMES
# ----------------------------
volumes:
  # Join an existing volume
  duplicati-config:
    name: duplicati-config

  # Create a new volume
  #duplicati-config:

networks:
  # Join an existing network
  proxy:
    name: proxy

# To create a network
#  proxy:
