#!/usr/bin/with-contenv sh

cd ${RTORRENT_HOME}

echo "[*] Starting rtorrent"
# Start rtorrent as daemon in backgroud
exec s6-setuidgid rtorrent rtorrent -n -o import=${RTORRENT_HOME}/rtorrent.rc > ${RTORRENT_HOME}/s6-start.log 2>&1 &

# Print rtorrent log (except for xmlprc logs)
until [ -f "log/execute.log" ] ; do
  sleep 1s
done
until [ -f log/rtorrent-*.log ] ; do
  sleep 1s
done

tail -f s6-start.log log/execute.log log/rtorrent-*.log
