# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  nextcloud:

    # Pull from GitHub
    image: linuxserver/nextcloud:17.0.1-ls50

    # Container name
    container_name: nextcloud

    # build
    #build:
    #  context: build/
    #  dockerfile: Dockerfile

    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false
    tty: false

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 10s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:nextcloud.lmilcent.com"
      traefik.port: "443"
      traefik.backend: "Nextcloud"
      traefik.docker.network: "proxy"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.protocol: "https"

    # Environment variables
    # For secrets with host environment variables
    environment:
      ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      DB_NAME: ${NEXTCLOUD_DB_NAME}

    # Public variables
    env_file: default.env
      
    # Volumes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud-data-new:/data:rw
      - nextcloud-config-new:/config:rw

    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 4
    mem_limit: 1024m
    memswap_limit: 1024m


    # -------
    # NETWORK
    # -------
    
    # Network
    networks:
      - proxy
      - nextcloud-backend

    #ports:


    # -----
    # OTHER
    # -----
    
    # Override entrypoints and command
    #entrypoint: /bin/bash
    #command: "printenv | grep TEST"


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETGID 
      - SETUID
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
    # Special rights (like create a TAP network card on the host)
    #privileged: true



  # Service name
  mariadb:

    # Pull from official repository
    image: mariadb:10.4.10

    # Container name
    container_name: nextcloud-db


    # -----------
    # COMPILATION
    # -----------
    #uild:
    #   context: .
    #   dockerfile: Dockerfile


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false

    # Add a tty
    tty: false

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    #labels:

    # Environment variables
    # For secrets with host environment variables
    environment:
      MYSQL_DATABASE: ${NEXTCLOUD_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${NEXTCLOUD_MYSQL_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    # Public variables 
    #env_file: default.env
      
    # Volumes
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - nextcloud-db:/var/lib/mysql:rw


    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 1
    mem_limit: 256m
    memswap_limit: 256m


    # -------
    # NETWORK
    # -------
    
    # Network
    networks:
      - nextcloud-backend


    # -----
    # OTHER
    # -----
    
    # Override entrypoints and command
    #entrypoint: /bin/sh 
    #command: "/bin/sh"


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL

    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
      - DAC_OVERRIDE



# ----------------------------
# CREATION: NETWORKS & VOLUMES
# ----------------------------
volumes:
  # Join an existing volume
  nextcloud-data-new:
    name: nextcloud-data-new

  nextcloud-config-new:
    name: nextcloud-config-new

  nextcloud-db:
    name: nextcloud-db

networks:
  # Join an existing network
  proxy:
    name: proxy

  nextcloud-backend:
    name: nextcloud-backend
