#!/usr/bin/with-contenv sh

# Init
echo "-----------------------------------------------"
echo "   _             _  _                     _ "
echo "  | |           (_)| |                   | |"
echo "  | | _ __ ___   _ | |  ___   ___  _ __  | |_"
echo "  | || '_ \ _ \ | || | / __| / _ \| '_ \ | __|"
echo "  | || | | | | || || || (__ |  __/| | | || |_"
echo "  |_||_| |_| |_||_||_| \___| \___||_| |_| \__|"
echo ""
echo "-----------------------------------------------"
echo " Application : rtorrent"
echo " Running user: rtorrent"
echo " Base OS     : Alpine"
echo "-----------------------------------------------"
echo " rTorrent configuration"
echo "   - Config file: ${RTORRENT_HOME}/rtorrent.rc"
echo "   - Log file   : ${RTORRENT_HOME}/s6-start.log"
echo "-----------------------------------------------"

cd ${RTORRENT_HOME}

echo "[*] Starting rtorrent"
# Start rtorrent as daemon in backgroud
exec s6-setuidgid rtorrent rtorrent -n -o import=${RTORRENT_HOME}/rtorrent.rc > ${RTORRENT_HOME}/s6-start.log 2>&1 &

# Print rtorrent log (except for xmlprc logs)
until [ -f "log/execute.log" ] ; do
  sleep 1s
done
until [ -f log/rtorrent-*.log ] ; do
  sleep 1s
done

tail -f s6-start.log log/execute.log log/rtorrent-*.log

