#!/usr/bin/with-contenv sh

# Init
echo "-----------------------------------------------"
echo "   _             _  _                     _ "
echo "  | |           (_)| |                   | |"
echo "  | | _ __ ___   _ | |  ___   ___  _ __  | |_"
echo "  | || '_ \ _ \ | || | / __| / _ \| '_ \ | __|"
echo "  | || | | | | || || || (__ |  __/| | | || |_"
echo "  |_||_| |_| |_||_||_| \___| \___||_| |_| \__|"
echo ""
echo "-----------------------------------------------"
echo " Application : ghost"
echo " Running user: app"
echo " Base OS     : Alpine"
echo "-----------------------------------------------"
echo " ghost configuration"
echo "   - Node mode  : ${NODE_ENV}"
echo "   - Config file: /ghost/config.production.json"
echo "-----------------------------------------------"


echo "[*] Applying rights"
cd /ghost/content
if [ ! -f "ghost.conf" ] ; then
  touch ghost.conf
fi
if [ ! -f "/ghost/config.development.json" ] ; then
  cp ghost.conf /ghost/config.development.json
fi
if [ ! -f "/ghost/config.production.json" ] ; then
  cp ghost.conf /ghost/config.production.json
fi
echo "NOTICE: It could be long as there is $(find /ghost -type f | wc -l) files."
find /ghost \! -user app -exec chown app:app {} \;


echo "[*] Starting Ghost"
cd /ghost
exec s6-setuidgid app /usr/local/bin/node index
