#!/usr/bin/with-contenv sh

UID=${UID:-8888}
GID=${GID:-8888}

# Init
echo "-----------------------------------------------"
echo "   _             _  _                     _ "
echo "  | |           (_)| |                   | |"
echo "  | | _ __ ___   _ | |  ___   ___  _ __  | |_"
echo "  | || '_ \ _ \ | || | / __| / _ \| '_ \ | __|"
echo "  | || | | | | || || || (__ |  __/| | | || |_"
echo "  |_||_| |_| |_||_||_| \___| \___||_| |_| \__|"
echo ""
echo "-----------------------------------------------"
echo " Application : Duplicati"
echo " Running user: app"
echo " User ID     : ${UID}"
echo " Group ID    : ${GID}"
echo " Base OS     : Debian"
echo "-----------------------------------------------"
echo " Duplicati configuration"
echo "   - Config folder : /config"
echo "-----------------------------------------------"

echo "[*] Applying setuid and permissions to /apply-backup-acl.sh"
chown root:root /apply-backup-acl.sh
chmod 4755 /apply-backup-acl.sh
chmod u+s /apply-backup-acl.sh

echo "[*] Applying acl to /backups/*"
export DUPLICATI__LOCALPATH="/backups"
export DUPLICATI__EVENTNAME="BEFORE"
export DUPLICATI__OPERATIONNAME="BACKUP"
/apply-backup-acl.sh


echo "[*] Applying rights to /config/*"
chown -R ${UID}:${GID} /config

echo "[*] Applying acl to /restore/*"
export DUPLICATI__LOCALPATH="/restore"
/apply-backup-acl.sh


# Unset duplicati default variables
unset DUPLICATI__LOCALPATH
unset DUPLICATI__EVENTNAME
unset DUPLICATI__OPERATIONNAME

# Erase old log file and restore permissions
echo > /config/server.log
chown ${UID}:${GID} /config/server.log

# Start duplicati in background and show logs in console
echo "[*] Starting Duplicati"
cd /duplicati
exec s6-setuidgid ${UID}:${GID} \
  mono Duplicati.Server.exe \
  --webservice-interface=any \
  --server-datafolder=/config \
  --webservice-allowed-hostnames=* \
  --log-level=Information \
  --log-file=/config/server.log  &

exec s6-setuidgid ${UID}:${GID} \
  tail -f /config/server.log
