#!/usr/bin/with-contenv sh

# Init
echo "-----------------------------------------------"
echo "   _             _  _                     _ "
echo "  | |           (_)| |                   | |"
echo "  | | _ __ ___   _ | |  ___   ___  _ __  | |_"
echo "  | || '_ \ _ \ | || | / __| / _ \| '_ \ | __|"
echo "  | || | | | | || || || (__ |  __/| | | || |_"
echo "  |_||_| |_| |_||_||_| \___| \___||_| |_| \__|"
echo ""
echo "-----------------------------------------------"
echo " Application : Duplicati"
echo " Running user: app"
echo " Base OS     : Debian"
echo "-----------------------------------------------"
echo " Duplicati configuration"
echo "   - Config folder : /config"
echo "-----------------------------------------------"

echo "[*] Starting"
exec s6-setuidgid app \
  mono Duplicati.Server.exe \
  --webservice-interface=any \
  --server-datafolder=/config
