#!/usr/bin/with-contenv sh

# Init
echo "-----------------------------------------------"
echo "   _             _  _                     _ "
echo "  | |           (_)| |                   | |"
echo "  | | _ __ ___   _ | |  ___   ___  _ __  | |_"
echo "  | || '_ \ _ \ | || | / __| / _ \| '_ \ | __|"
echo "  | || | | | | || || || (__ |  __/| | | || |_"
echo "  |_||_| |_| |_||_||_| \___| \___||_| |_| \__|"
echo ""
echo "-----------------------------------------------"
echo " Application : Duplicati"
echo " Running user: app"
echo " Base OS     : Debian"
echo "-----------------------------------------------"
echo " Duplicati configuration"
echo "   - Config folder : /config"
echo "-----------------------------------------------"

echo "[*] Applying permissions to /apply-backup-group.sh"
chmod +rx /apply-backup-group.sh
chown -R root:app /apply-backup-group.sh
# Allow user "app" to run the script as root
echo "app     ALL=(ALL) NOPASSWD: /apply-backup-group.sh" >> /etc/sudoers

echo "[*] Applying permissions to /config"
chown -R app:app /config

echo "[*] Applying permissions to /restore"
chown -R app:1111 /restore

# duplicati-backups really exist on the docker host
# This allow the container to read some files and folders
echo "[*] Applying permissions to /backups"
groupadd --gid 1111 duplicati-backup
chgrp -R duplicati-backup /backups

echo "[*] Starting Duplicati"
# UID 991 = app
cd /duplicati
exec s6-setuidgid 991:1111 \
  mono Duplicati.Server.exe \
  --webservice-interface=any \
  --server-datafolder=/config \
  --webservice-allowed-hostnames=*
