# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  netdata:

    # Download the image or build it
    image: netdata/netdata:latest
    #image: lmilcent/netdata

    container_name: netdata

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 5s
    stop_signal: SIGTERM

    # Environment variables
    environment: 
      DO_NOT_TRACK: 1
      TZ: Europe/Paris

    labels:
      # Base
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.netdata.entrypoints: "websecure"
      traefik.http.routers.netdata.middlewares: "security@file, compression@file"
      traefik.http.routers.netdata.tls: "true"
      traefik.http.routers.netdata.tls.certresolver: "certMilcent"

      # Specific
      traefik.http.routers.netdata.rule: "Host(`monitoring.milcent.co`) || Host(`monitoring.lmilcent.com`)"
      traefik.http.routers.netdata.middlewares: "netdata-auth"
      traefik.http.middlewares.netdata-auth.basicauth.users: "monitoring:${NETDATA_BASIC_AUTH}"

    # Volumes
    volumes:
      - netdata-lib:/var/lib/netdata:rw
      - netdata-cache:/var/cache/netdata:rw
      - netdata-config:/etc/netdata:rw
      - /dev/mapper:/host/dev/mapper:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/shadow:/host/etc/shadow:ro
      - /etc/group:/host/etc/group:ro
      #- /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/host/var/run/docker.sock:ro

    # Limit resources
    cpus: 2
    mem_limit: 512m
    memswap_limit: 512m

    # Network
    networks:
      - proxy

    # Drop capabilities (man 7 capabilities for list)
#    cap_drop:
#      - ALL
    cap_add:
       - SYS_PTRACE
#      - CHOWN
#      - FSETID
#      - SETGID
#      - SETUID
#      - DAC_OVERRIDE
#      - SYS_PTRACE
    #userns_mode: host
    #privileged: true
    security_opt:
      - apparmor:unconfined 
      - no-new-privileges=false

# --------
# NETWORKS
# --------
networks:
  proxy:
    name: proxy

volumes:
  netdata-config:
    name: netdata-config
  netdata-cache:
    name: netdata-cache
  netdata-lib:
    name: netdata-lib
