# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  ghost:

    # Build Ghost from GitHub, check manually the last version
    # https://github.com/TryGhost/Ghost/releases
    image: lmilcent/ghost:3.37.1-distroless

    # Container name
    container_name: ghost


    # -----------
    # COMPILATION
    # -----------
    build:
      context: .
      dockerfile: Dockerfile


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: true

    # Add a tty
    tty: true

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------
    labels:
      # Base
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.ghost.entrypoints: "websecure"
      traefik.http.routers.ghost.middlewares: "security@file, compression@file"
      traefik.http.routers.ghost.tls: "true"
      traefik.http.routers.ghost.tls.certresolver: "certMilcent"

      # Specific
      traefik.http.routers.ghost.rule: "Host(`blog.milcent.co`) || Host(`blog.lmilcent.com`)"


    # Environment variables
    # For secrets with host environment variables
    environment: 
      database__connection__password: ${GHOST_DB_SECRET}
      mail__options__host: ${GHOST_SMTP_HOST}
      mail__options__auth__user: ${GHOST_SMTP_USER}
      mail__options__auth__pass: ${GHOST_SMTP_SECRET}
    # Public variables
    env_file: ghost.env
      
    # Volumes
    volumes:
      - /data/ghost/content:/ghost/content:z


    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 2
    mem_limit: 1024m
    memswap_limit: 1024m
    pids_limit: 100 # 11 on idle

    # -------
    # NETWORK
    # -------
    
    # Network
    networks:
      - proxy
      - ghost-backend


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    #cap_drop:

    #cap_add:
    #  - CAP_CHOWN
    #  - CAP_FOWNER






  # Service name
  mysql:

    # Pull from GitHub
    #image: mariadb:5.5
    image: mariadb:10.5

    # Container name
    container_name: ghost-db


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false
    tty: false

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    #labels:

    # Environment variables
    # For secrets with host environment variables
    environment: 
      MYSQL_ROOT_PASSWORD: ${GHOST_MYSQL_ROOT_SECRET}
      MYSQL_PASSWORD: ${GHOST_MYSQL_SECRET}

    # Public variables
    env_file: mysql.env
      
    # Volumes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/ghost/db/data:/var/lib/mysql:z
 

    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 1
    mem_limit: 256m
    memswap_limit: 256m


    # -------
    # NETWORK
    # -------
    
    # Network
    networks:
      - ghost-backend


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    #cap_drop:
    #  - ALL
    #cap_add:
    #  - CHOWN
    #  - FOWNER
    #  - SETGID 
    #  - SETUID
    #  - DAC_OVERRIDE




# ----------------------------
# CREATION: NETWORKS & VOLUMES
# ----------------------------
networks:
  # Join an existing network
  proxy:
    name: proxy

  ghost-backend:
    name: ghost-backend
