# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  syncthing:

    # Pull from GitHub
    image: ghcr.io/linuxserver/syncthing

    # Container name
    container_name: syncthing

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 10s
    stop_signal: SIGTERM

    # Environment variables
    # For secrets with host environment variables
    environment:
      PUID: 9999
      PGID: 9999
      TZ: Europe/Paris

    # Volumes
    # To allow access to all files, create a ACL rule on host.
    # UID 9999 => 241071 on host if user namespace is enabled within Docker
    # execute for (read only everywhere): setfact -R -m user:241071:rX /data && setfact -R -m group:241071:rX /data
    # to reset ACL:  setfact -bn /data
    volumes:
      - /data/syncthing/appdata/config:/config:z
      - /data:/data:z

    # Ports
    ports:
      - 22000:22000
      - 21027:21027/udp

    # Network
    networks:
      - proxy

    # Labels
    labels:
      # Base
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.syncthing.entrypoints: "websecure"
      traefik.http.routers.syncthing.middlewares: "security@file, compression@file"
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.tls.certresolver: "certMilcent"

      # Specific
      traefik.http.routers.syncthing.rule: "Host(`syncthing.milcent.co`) || Host(`syncthing.lmilcent.com`)"
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
      traefik.http.services.syncthing.loadbalancer.server.scheme: "https"

    # Limit resources
    cpus: 1
    mem_limit: 512m
    memswap_limit: 512m
    pids_limit: 100 # ? in idle
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETGID 
      - SETUID
      - DAC_OVERRIDE

networks:
  proxy:
    name: proxy
