# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'

services:

  # Service name
  photoprism:

    image: photoprism/photoprism:latest
    container_name: photoprism

    # no / always / on-failure / unless-stopped
    restart: unless-stopped

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 15s
    stop_signal: SIGTERM

    depends_on:
      - photoprism-db

    labels:
      # Base
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.photoprism.entrypoints: "websecure"
      traefik.http.routers.photoprism.middlewares: "security@file, compression@file"
      traefik.http.routers.photoprism.tls: "true"
      traefik.http.routers.photoprism.tls.certresolver: "certMilcent"

      # Specific
      traefik.http.routers.photoprism.rule: "Host(`photo.milcent.co`) || Host(`photo.lmilcent.com`)"
      # Services
      traefik.http.services.photoprism.loadbalancer.server.port: 2342
      #traefik.http.services.photoprism.loadbalancer.server.scheme: "http"

    # Volumes
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - /data/syncthing/appdata/config/Camera/Camera:/photoprism/originals/Camera:rw,z
      - /data/syncthing/appdata/config/Collections:/photoprism/originals/Collections:rw,z
      # Mounting an import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - /data/photoprism/storage:/photoprism/storage:rw,z

    # Limit resources
    cpus: 2
    mem_limit: 2048m
    memswap_limit: 2048m

    environment:
      UID: 9999
      GID: 9999
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_HTTP_PORT: 2342                     # Built-in Web server port
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "photoprism-db:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "${PHOTOPRISM_DATABASE_PASSWORD}"              # MariaDB database user password
      PHOTOPRISM_SITE_URL: "https://photo.milcent.co"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: "Louis"
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      # UID: 1000
      # GID: 1000
      # UMASK: 0000

    # Uncomment and edit the following line to set a specific user / group id (native):
    # user: "1000:1000"

    networks:
      - proxy
      - photoprism-backend

    
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    #cap_drop:

    #cap_add:
    #  - CAP_CHOWN
    #  - CAP_FOWNER

    pids_limit: 200

    # Solve "mkdir /var/run/s6: Permission denied"
    # And to be able to use setfacl
    #userns_mode: host
    #security_opt:
    #  - no-new-privileges=false 
    #  - apparmor:unconfined



  photoprism-db:
    image: mariadb:10.5
    container_name: photoprism-db
    restart: unless-stopped
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - /data/photoprism/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PHOTOPRISM_DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: ${PHOTOPRISM_DATABASE_PASSWORD}
    networks:
      - photoprism-backend


# ----------------------------
# CREATION: NETWORKS & VOLUMES
# ----------------------------
networks:
  proxy:
    name: proxy
  photoprism-backend:
    name: photoprism-backend
