# Version 2.0 mandatory for CPU limiting
# See: https://github.com/docker/compose/issues/4513

version: '2.4'


services:

  # Service name
  sslh:

    # Build sslh  from last release for alpine
    image: lmilcent/sslh:1.20-r1

    # Container name
    container_name: sslh


    # -----------
    # COMPILATION
    # -----------
    build:
        context: .
        dockerfile: Dockerfile


    # -------
    # STARTUP
    # -------

    # Mode interactive
    stdin_open: false

    # Add a tty
    tty: false

    # no / always / on-failure / unless-stopped
    restart: on-failure

    # Stop delay (1s, 1m30s, etc.) and signal (SIGTERM is default)
    stop_grace_period: 5s
    stop_signal: SIGTERM


    # ---------------------
    # LABELS, ENV & VOLUMES
    # ---------------------

    #labels:

    # Environment variables
    # For secrets with host environment variables
    env_file: default.env
      
    # Volumes
    volumes:
      - /etc/localtime:/etc/localtime:ro


    # ---------
    # RESOURCES
    # ---------

    # Limit resources
    cpus: 0.5
    mem_limit: 512m
    memswap_limit: 512m


    # -------
    # NETWORK
    # -------
    
    # Expose port to linked services (internal only)
    #expose:
    
    # Expose port to ALL
    ports:
      - 443:443/tcp

    # Network
    networks:
      - proxy


    # -----
    # OTHER
    # -----
    
    # Override entrypoints and command
    #entrypoint: /bin/bash
    #command: "printenv | grep TEST"


    # --------
    # SECURITY
    # --------
    
    # Drop capabilities (man 7 capabilities for list)
    # Should drop ALL by default
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SETFCAP


# ----------------------------
# CREATION: NETWORKS & VOLUMES
# ----------------------------
networks:
  # Join an existing network
  proxy:
    name: proxy
