#!/usr/bin/with-contenv bash

# Init
echo "-----------------------------------------------"
echo "   _             _  _                     _ "
echo "  | |           (_)| |                   | |"
echo "  | | _ __ ___     | |  ___   ___  _ __  | |_"
echo "  | || '_ \ _ \ | || | / __| / _ \| '_ \ | __|"
echo "  | || | | | | || || || (__ |  __/| | | || |_"
echo "  |_||_| |_| |_||_||_| \___| \___||_| |_| \__|"
echo ""
echo "-----------------------------------------------"
echo " Application : netdata"
echo " Running user: app"
echo " Base OS     : Alpine"
echo "-----------------------------------------------"
echo " netdata configuration"
echo "   - Listen     : ${LISTEN_IP}:${LISTEN_PORT}"
echo "-----------------------------------------------"



# Applying perms
echo && echo "[*] Applying permissions"
#setcap SYS_PTRACE=+eip /opt/netdata/bin/srv/netdata
# find /app \! -user netdata -exec chown netdata:netdata {} \;

# Init config file
echo && echo "[*] Initialisation"
# touch /app/netdata.conf

# Start SSLH with lower rights
echo && echo "[*] Starting"
# exec s6-setuidgid netdata \
#    /app/netdata/bin/srv/netdata -D \
#      -u netdata \
#      -s /host \
#      -i ${LISTEN_IP} \
#      -p ${LISTEN_PORT} \
#      -c /app/netdata.conf \
#       $@

exec /usr/sbin/netdata -D -c /etc/netdata/netdata.conf -u netdata -s /host -i ${LISTEN_IP} -p ${LISTEN_PORT}
